title: 이영훈 - 사운드 디자인 포트폴리오
description: 게임, 영상에 생명을 불어넣는 사운드 디자이너 이영훈입니다.
site_title: '@yeonghun - Sound Designer'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
email: aa_bb33@naver.com
phone: 010-3399-5382

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 